document.writeln("<table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"tuijian\">");
document.writeln("<tr>");
document.writeln("<td class=\"t\"><strong>推荐栏：<\/strong><a href=\"http:\/\/www.wangzhi8.com\/cms\/joke\/\" target=\"_blank\">幽默笑话<\/a>");
document.writeln("<a href=\"http:\/\/www.wangzhi8.com\/cms\/miyu\/\" target=\"_blank\">谜语大全<\/a>");
document.writeln("<a href=\"http:\/\/www.wangzhi8.com\/cms\/qq\/qqzone\/2008072613770.html\" target=\"_blank\">Q币<\/a>");
document.writeln("<a href=\"http:\/\/www.wangzhi8.com\/cms\/joke\/sort012\/16950.html\" target=\"_blank\">女人偷看黄色网站后<\/a>");
document.writeln("<\/td>");
document.writeln("<td width=\"170\"><iframe width=\"168\" height=\"20\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\" scrolling=\"no\" src=\"http:\/\/news.sina.com.cn\/iframe\/2009\/1230\/408.html\"><\/iframe><\/td>");
document.writeln("<td width=\"130\"><a href=\"http:\/\/www.wangzhi8.com\/\" onClick=\"this.style.behavior=\'url(#default#homepage)\';this.setHomePage(\'http:\/\/www.wangzhi8.com\/\');return(false);\" style=\"behavior: url(#default#homepage)\">将网址大宝库设为首页<\/a><\/td>");
document.writeln("<\/tr>");
document.writeln("<\/table>");
document.writeln("<table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"biaoti\">");
document.writeln("<tr>");
document.writeln("<td width=\"150\" align=\"center\"><a href=\"\/\"><img border=\"0\" src=\"images\/ade8logo.gif\" width=\"139\" height=\"60\" alt=\"网址大宝库\"><\/a><\/td>");
document.writeln("<td width=\"800\" align=\"right\"><iframe marginheight=\"0\" marginwidth=\"0\" frameborder=\"0\" width=\"798\" height=\"60\" scrolling=\"no\" src=\"..\/js\/banner.html\"><\/iframe><\/td>");
document.writeln("<\/tr>");
document.writeln("<\/table>");